### ISSUE TITLE
Question. Does there is opposite to this library like ESTree -> JSON

### ISSUE THREAD

**Issue by dimaMachina** [remcohaszing/estree-util-value-to-estree#2] opened 2023-09-07 10:10 UTC
Hi! Thanks for your library.

I am looking for the opposite library to convert `ObjectExpression` from `ESTree` to `JSON`. Any thougout?

**Comment by remcohaszing** [comment] 2023-09-07 11:40
Good question. I have thought about this myself as well.

The problem is that estree may contain a lot more that what this library can produce. For example, estree may contain function calls, if-statements, and other control flow expressions that are simply not relevant to represent a simple value as `estree-util-value-to-estree` does.

I suppose it would be possible to write such a function where you limit support to specific value. I imagine it would look something like this:

```js
export function estreeToValue(node: Expression) {
  switch(node.type) {
    case 'Literal':
      return node.value 
    case 'UnaryExpression':
      if (node.operator === '-') {
        return -estreeToValue(node.argument)
      }
      if (node.operator === '+') {
        return +estreeToValue(node.argument)
      }
    // Etc…
  }
}
```

This will work now, but there is no guarantee a later version `estree-util-value-to-estree` won’t produce nodes that this new function can’t handle.

For example, one thing that’s still missing from `estree-util-value-to-estree` is common references.

```js
const a = {}
const b = {
  // In the result of estree-util-value-to-estree b.c is not equal to b.d
  c: a,
  d: a
}

const r = {}
// This object will cause `estree-util-value-to-estree` to recursive indefinitely
r.r = r
```

To serialize such a value correctly, `estree-util-value-to-estree` would need to generate an iife. That’s going to be really hard to handle for an inverse algorithm.

---

I recommend to use the same approach as in the [tests](https://github.com/remcohaszing/estree-util-value-to-estree/blob/main/test.ts#L61-L67): Use `astring` to generate the value, then evaluate using the `Function` constructor. Of course you should only evaluate content you trust.

```js
import assert from 'node:assert/strict'
import { generate } from 'astring'
import { valueToEstree } from 'estree-util-value-to-estree'

function estreeToValue(estree) {
  const code = generate(estree)
  const getValue = new Function(`return ${code}`)
  return getValue()
}

const value = { some: { complex: [,,, 'value',,, ] } }

assert.equal(
  estreeToValue(valueToEstree(value)),
  value
)
```

I’m closing this issue because it’s a question. Feel free to add more comments. It’s an interesting subject. :)

**Closed as not planned by remcohaszing** 2023-09-07 11:40 UTC
Labels: question

**Comment by dimaMachina** [comment] 2023-09-07 14:33
@remcohaszing thank you very much for your detailed answer! 🎉

I guess I will write something to parse only `Literal` (string/number/boolean/null) and `ArrayExpression` and `ObjectExpression`  nodes to be safe and avoid evaluating using the `Function`, the rest of things I'll just skip

```js
const foo = {
  a: 'foo',
  b: true,
  c: 22,
  n: null,
  z: [...],
  d: {...}
}
```

**Comment by remcohaszing** [comment] 2024-04-05 08:46
Your best option to evaluate an estree expression is [`sval`](https://github.com/Siubaak/sval).

The upcoming minor version of `value-to-estree` release will add an option to preserve references, which also supports cyclical references. The next major version will flip this option, making it the default behaviour.
